class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'tr': {
      'app_title': 'Ezan Hatırlatıcı',
      'settings': 'Ayarlar',
      'about': 'Hakkında',
      'qibla': 'Kıble Pusulası',
      'language': 'Dil Seçimi',
      'language_desc': 'Uygulama dilini değiştirin',
      'turkish': 'Türkçe 🇹🇷',
      'english': 'English 🇬🇧',
      'next_prayer': 'SONRAKİ VAKİT',
      'time_remaining': 'Kalan Süre',
      'todays_prayers': 'Bugünün Namaz Saatleri',
      'location': 'Konum',
      'change': 'Değiştir',
      'unknown': 'Bilinmiyor',
      'fajr': 'Sabah Namazı',
      'sunrise': 'Güneş',
      'dhuhr': 'Öğle Namazı',
      'asr': 'İkindi Namazı',
      'maghrib': 'Akşam Namazı',
      'isha': 'Yatsı Namazı',
      'notification_settings': 'Bildirim Ayarları 🔔',
      'notification_sound': 'Bildirim Sesi',
      'notification_sound_desc': 'Vakit yaklaştığında sesli uyarı ver',
      'vibration': 'Titreşim',
      'vibration_desc': 'Bildirim geldiğinde cihazı titreştir',
      'select_notification_sound': 'Bildirim Sesi Seçimi',
      'select_sound_sub': 'Namaz vakti veya hatırlatmada çalacak olan sesi tercih edin:',
      'sound_makkah': 'Mekke Ezanı',
      'sound_makkah_sub': 'Klasik ve heybetli Mekke-i Mükerreme Ezanı',
      'sound_madinah': 'Medine Ezanı',
      'sound_madinah_sub': 'Huzur veren Medine-i Münevvere Ezanı',
      'sound_ney': 'Huzurlu Ney Tonu',
      'sound_ney_sub': 'Yumuşak ve dinlendirici enstrümantal ses',
      'sound_beep': 'Kısa Bip Sesi',
      'sound_beep_sub': 'Sade ve kısa uyarı tonu',
      'test_notification': 'Test Bildirimi Gönder',
      'test_notification_sent': 'Test bildirimi gönderildi! 🔔',
      'reminder_times': 'Hatırlatma Süreleri ⏰',
      'reminder_times_desc': 'Her vakitten ne kadar süre önce bildirim almak istediğinizi belirleyin:',
      'on_time': 'Vakit girince',
      'min_before': 'dakika önce',
      'exact_time': 'Tam Vaktinde',
      'qibla_angle': 'Kıble Açısı',
      'distance_to_kaaba': 'Kâbe\'ye Uzaklık',
      'qibla_aligned': 'Kıble Yönündesiniz! 🕌',
      'qibla_guide': '💡 Telefonunuzu düz bir zeminde tutun ve sarı ok tam yukarı gelene kadar cihazınızı döndürün.',
      'device_heading': 'Cihaz Yönü (Pusula Ayarı)',
      'about_description': 'Ezan Hatırlatıcı, dünya genelinde doğru namaz vakitleri, canlı sayaçlar, özelleştirilebilir hatırlatmalar ve Kıble pusulası sunan modern bir İslami yardımcı uygulamadır.',
      'version': 'Sürüm',
      'developer': 'Geliştirici',
      'data_source': 'Veri Kaynağı',
      'audio_source': 'Ses Kaynakları',
      'aladhan_api': 'Aladhan REST API (Dünya genel namaz saatleri)',
      'audio_recitations': 'Mekke & Medine Ezan Kayıtları (Haramain Audio)',
      'features': 'Öne Çıkan Özellikler',
      'feature_1': '⏱️ Canlı Vakit Geri Sayım Sayacı',
      'feature_2': '🔔 Özelleştirilebilir Zamanlanmış Bildirimler',
      'feature_3': '🕌 Mekke & Medine İnsan Sesli Ezan Kayıtları',
      'feature_4': '🧭 Hassas Kıble Pusulası & Hizalama Uyarısı',
      'feature_5': '📶 Çevrimdışı Önbellekleme Desteği',
      'feature_6': '🌍 Türkçe & İngilizce Çift Dil Desteği',
      'license': 'Lisans',
      'mit_license': 'MIT Açık Kaynak Lisansı',
      'rate_app': 'Uygulamayı Değerlendir & Geri Bildirim',
    },
    'en': {
      'app_title': 'Prayer Times Reminder',
      'settings': 'Settings',
      'about': 'About',
      'qibla': 'Qibla Compass',
      'language': 'Language Selection',
      'language_desc': 'Change application language',
      'turkish': 'Türkçe 🇹🇷',
      'english': 'English 🇬🇧',
      'next_prayer': 'NEXT PRAYER',
      'time_remaining': 'Time Remaining',
      'todays_prayers': 'Today\'s Prayer Times',
      'location': 'Location',
      'change': 'Change',
      'unknown': 'Unknown',
      'fajr': 'Fajr (Dawn)',
      'sunrise': 'Sunrise',
      'dhuhr': 'Dhuhr (Noon)',
      'asr': 'Asr (Afternoon)',
      'maghrib': 'Maghrib (Sunset)',
      'isha': 'Isha (Night)',
      'notification_settings': 'Notification Settings 🔔',
      'notification_sound': 'Notification Sound',
      'notification_sound_desc': 'Play alert sound when prayer time approaches',
      'vibration': 'Vibration',
      'vibration_desc': 'Vibrate device upon notification',
      'select_notification_sound': 'Notification Sound Selection',
      'select_sound_sub': 'Choose your preferred recitation tone for prayer reminders:',
      'sound_makkah': 'Makkah Adhan',
      'sound_makkah_sub': 'Classic & majestic Makkah Al-Mukarramah Adhan',
      'sound_madinah': 'Madinah Adhan',
      'sound_madinah_sub': 'Peaceful Madinah Al-Munawwarah Adhan',
      'sound_ney': 'Peaceful Ney Tone',
      'sound_ney_sub': 'Soft & relaxing instrumental sound',
      'sound_beep': 'Short Beep Tone',
      'sound_beep_sub': 'Simple and concise alert tone',
      'test_notification': 'Send Test Notification',
      'test_notification_sent': 'Test notification sent! 🔔',
      'reminder_times': 'Reminder Times ⏰',
      'reminder_times_desc': 'Set how many minutes before each prayer you wish to be notified:',
      'on_time': 'At prayer time',
      'min_before': 'min before',
      'exact_time': 'Exact Time',
      'qibla_angle': 'Qibla Angle',
      'distance_to_kaaba': 'Distance to Kaaba',
      'qibla_aligned': 'You are Facing Qibla! 🕌',
      'qibla_guide': '💡 Keep device flat and rotate until yellow arrow points directly up.',
      'device_heading': 'Device Heading (Compass Adjustment)',
      'about_description': 'Prayer Times Reminder is a modern Islamic utility app offering accurate global prayer schedules, live countdowns, custom reminders, and Qibla compass.',
      'version': 'Version',
      'developer': 'Developer',
      'data_source': 'Data Source',
      'audio_source': 'Audio Sources',
      'aladhan_api': 'Aladhan REST API (Global prayer timings)',
      'audio_recitations': 'Makkah & Madinah Vocal Recitations (Haramain Audio)',
      'features': 'Key Features',
      'feature_1': '⏱️ Live Prayer Countdown Timer',
      'feature_2': '🔔 Customizable Scheduled Local Notifications',
      'feature_3': '🕌 Authentic Makkah & Madinah Vocal Adhans',
      'feature_4': '🧭 Precision Qibla Compass & Alignment Alert',
      'feature_5': '📶 Offline Caching & Auto Re-sync',
      'feature_6': '🌍 Multilingual TR & EN Support',
      'license': 'License',
      'mit_license': 'MIT Open Source License',
      'rate_app': 'Rate App & Send Feedback',
    },
  };

  static String get(String key, String langCode) {
    final lang = _localizedValues.containsKey(langCode) ? langCode : 'tr';
    return _localizedValues[lang]?[key] ?? _localizedValues['tr']?[key] ?? key;
  }
}
