class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'tr': {
      'app_title': 'Ezan Hatırlatıcı',
      'settings': 'Ayarlar',
      'about': 'Hakkında',
      'qibla': 'Kıble Pusulası',
      'language': 'Dil Seçimi',
      'language_desc': 'Uygulama dilini değiştirin',
      'turkish': 'Türkçe 🇹🇷',
      'english': 'English 🇬🇧',
      'next_prayer': 'SONRAKİ VAKİT',
      'time_remaining': 'Kalan Süre',
      'todays_prayers': 'Bugünün Namaz Saatleri',
      'location': 'Konum',
      'change': 'Değiştir',
      'unknown': 'Bilinmiyor',
      'current_location': 'Mevcut Konum',
      'fajr': 'Sabah Namazı',
      'sunrise': 'Güneş',
      'dhuhr': 'Öğle Namazı',
      'asr': 'İkindi Namazı',
      'maghrib': 'Akşam Namazı',
      'isha': 'Yatsı Namazı',
      'notification_settings': 'Bildirim Ayarları 🔔',
      'notification_sound': 'Bildirim Sesi',
      'notification_sound_desc': 'Vakit yaklaştığında sesli uyarı ver',
      'vibration': 'Titreşim',
      'vibration_desc': 'Bildirim geldiğinde cihazı titreştir',
      'select_notification_sound': 'Bildirim Sesi Seçimi',
      'select_sound_sub': 'Namaz vakti veya hatırlatmada çalacak olan sesi tercih edin:',
      'sound_makkah': 'Mekke Ezanı 🕋',
      'sound_makkah_sub': 'Klasik ve heybetli Mekke-i Mükerreme Ezanı',
      'sound_madinah': 'Medine Ezanı 🕌',
      'sound_madinah_sub': 'Huzur veren Medine-i Münevvere Ezanı',
      'sound_istanbul': 'İstanbul Ezanı 🇹🇷',
      'sound_istanbul_sub': 'Geleneksel Türk makamında İstanbul Ezanı',
      'sound_cairo': 'Mısır Ezanı 🇪🇬',
      'sound_cairo_sub': 'Mısır makamında yanık ve etkileyici Ezan',
      'sound_aqsa': 'Mescid-i Aksa Ezanı 🇵🇸',
      'sound_aqsa_sub': 'Kudüs Mescid-i Aksa ruhunu yansıtan Ezan',
      'adhan_makkah': 'Mekke-i Mükerreme Ezanı 🕋',
      'adhan_madinah': 'Medine-i Münevvere Ezanı 🕌',
      'adhan_istanbul': 'İstanbul (Türkiye) Ezanı 🇹🇷',
      'adhan_cairo': 'Mısır (Kahire) Ezanı 🇪🇬',
      'adhan_aqsa': 'Mescid-i Aksa (Kudüs) Ezanı 🇵🇸',
      'sound_ney': 'Huzurlu Ney Tonu 🎶',
      'sound_ney_sub': 'Yumuşak ve dinlendirici enstrümantal ses',
      'sound_beep': 'Kısa Bip Sesi 🔔',
      'sound_beep_sub': 'Sade ve kısa uyarı tonu',
      'test_notification': 'Test Bildirimi Gönder',
      'test_notification_sent': 'Test bildirimi gönderildi! 🔔',
      'reminder_times': 'Hatırlatma Süreleri ⏰',
      'reminder_times_desc': 'Her vakitten ne kadar süre önce bildirim almak istediğinizi belirleyin:',
      'on_time': 'Vakit girince',
      'min_before': 'dakika önce',
      'exact_time': 'Tam Vaktinde',
      'qibla_angle': 'Kıble Açısı',
      'distance_to_kaaba': 'Kâbe\'ye Uzaklık',
      'qibla_aligned': 'Kıble Yönündesiniz! 🕌',
      'qibla_guide': '💡 Telefonunuzu düz bir zeminde tutun ve sarı ok tam yukarı gelene kadar cihazınızı döndürün.',
      'device_heading': 'Cihaz Yönü (Pusula Ayarı)',
      'about_description': 'Ezan Hatırlatıcı, dünya genelinde doğru namaz vakitleri, canlı sayaçlar, özelleştirilebilir hatırlatmalar ve Kıble pusulası sunan modern bir İslami yardımcı uygulamadır.',
      'version': 'Sürüm',
      'developer': 'Geliştirici',
      'data_source': 'Veri Kaynağı',
      'audio_source': 'Ses Kaynakları',
      'aladhan_api': 'Aladhan REST API (Dünya genel namaz saatleri)',
      'audio_recitations': 'Mekke & Medine Ezan Kayıtları (Haramain Audio)',
      'features': 'Öne Çıkan Özellikler',
      'feature_1': '⏱️ Canlı Vakit Geri Sayım Sayacı',
      'feature_2': '🔔 Özelleştirilebilir Zamanlanmış Bildirimler',
      'feature_3': '🕌 Mekke & Medine İnsan Sesli Ezan Kayıtları',
      'feature_4': '🧭 Hassas Kıble Pusulası & Hizalama Uyarısı',
      'feature_5': '📶 Çevrimdışı Önbellekleme Desteği',
      'feature_6': '🌍 Türkçe & İngilizce Çift Dil Desteği',
      'license': 'Lisans',
      'mit_license': 'MIT Açık Kaynak Lisansı',
      'rate_app': 'Uygulamayı Değerlendir & Geri Bildirim',
      'github_repo': 'GitHub Proje Deposu (Açık Kaynak Kodlar)',
      'theme_selection': 'Görünüm Teması 🎨',
      'theme_system': 'Sistem 📱',
      'theme_light': 'Aydınlık ☀️',
      'theme_dark': 'Karanlık 🌙',
      'retry': 'Tekrar Dene',
      'prayer_load_error': 'Namaz saatleri yüklenemedi',
      'use_gps_location': 'GPS ile Konumumu Al 📡',
      'select_city': 'Şehir Seç',
      'search_city': 'Şehir ara...',
      'stop_audio': 'Sesi Durdur',
      'stop_adhan_playing': 'Ezan Çalıyor... Sesi Durdur 🛑',
      'asr_school': 'İkindi Hesaplama Metodu (Mezhep)',
      'asr_school_desc': 'İkindi vakti hesaplama standardını belirleyin',
      'asr_standard': 'Standart (Şafiî, Malikî, Hanbelî)',
      'asr_hanafi': 'Hanefî (Asr-ı Sani)',
      'monthly_times': 'Aylık Takvim 🗓️',
      'monthly_title': 'Aylık Namaz Vakitleri 🗓️',
      'day': 'Gün',
      'date': 'Tarih',
    },
    'en': {
      'app_title': 'Prayer Times Reminder',
      'settings': 'Settings',
      'about': 'About',
      'qibla': 'Qibla Compass',
      'language': 'Language Selection',
      'language_desc': 'Change application language',
      'turkish': 'Türkçe 🇹🇷',
      'english': 'English 🇬🇧',
      'next_prayer': 'NEXT PRAYER',
      'time_remaining': 'Time Remaining',
      'todays_prayers': 'Today\'s Prayer Times',
      'location': 'Location',
      'change': 'Change',
      'unknown': 'Unknown',
      'current_location': 'Current Location',
      'fajr': 'Fajr (Dawn)',
      'sunrise': 'Sunrise',
      'dhuhr': 'Dhuhr (Noon)',
      'asr': 'Asr (Afternoon)',
      'maghrib': 'Maghrib (Sunset)',
      'isha': 'Isha (Night)',
      'notification_settings': 'Notification Settings 🔔',
      'notification_sound': 'Notification Sound',
      'notification_sound_desc': 'Play alert sound when prayer time approaches',
      'vibration': 'Vibration',
      'vibration_desc': 'Vibrate device upon notification',
      'select_notification_sound': 'Notification Sound Selection',
      'select_sound_sub': 'Choose your preferred recitation tone for prayer reminders:',
      'sound_makkah': 'Makkah Adhan 🕋',
      'sound_makkah_sub': 'Classic & majestic Makkah Al-Mukarramah Adhan',
      'sound_madinah': 'Madinah Adhan 🕌',
      'sound_madinah_sub': 'Peaceful Madinah Al-Munawwarah Adhan',
      'sound_istanbul': 'Istanbul Adhan 🇹🇷',
      'sound_istanbul_sub': 'Traditional Turkish style Istanbul Adhan',
      'sound_cairo': 'Cairo Adhan 🇪🇬',
      'sound_cairo_sub': 'Melodic & emotional Egyptian style Adhan',
      'sound_aqsa': 'Al-Aqsa Adhan 🇵🇸',
      'sound_aqsa_sub': 'Spiritual Adhan from Jerusalem Al-Aqsa',
      'sound_ney': 'Peaceful Ney Tone 🎶',
      'sound_ney_sub': 'Soft & relaxing instrumental sound',
      'sound_beep': 'Short Beep Tone 🔔',
      'sound_beep_sub': 'Simple and concise alert tone',
      'test_notification': 'Send Test Notification',
      'test_notification_sent': 'Test notification sent! 🔔',
      'reminder_times': 'Reminder Times ⏰',
      'reminder_times_desc': 'Set how many minutes before each prayer you wish to be notified:',
      'on_time': 'At prayer time',
      'min_before': 'min before',
      'exact_time': 'Exact Time',
      'qibla_angle': 'Qibla Angle',
      'distance_to_kaaba': 'Distance to Kaaba',
      'qibla_aligned': 'You are Facing Qibla! 🕌',
      'qibla_guide': '💡 Keep device flat and rotate until yellow arrow points directly up.',
      'device_heading': 'Device Heading (Compass Adjustment)',
      'about_description': 'Prayer Times Reminder is a modern Islamic utility app offering accurate global prayer schedules, live countdowns, custom reminders, and Qibla compass.',
      'version': 'Version',
      'developer': 'Developer',
      'data_source': 'Data Source',
      'audio_source': 'Audio Sources',
      'aladhan_api': 'Aladhan REST API (Global prayer timings)',
      'audio_recitations': 'Makkah & Madinah Vocal Recitations (Haramain Audio)',
      'features': 'Key Features',
      'feature_1': '⏱️ Live Prayer Countdown Timer',
      'feature_2': '🔔 Customizable Scheduled Local Notifications',
      'feature_3': '🕌 Authentic Makkah & Madinah Vocal Adhans',
      'feature_4': '🧭 Precision Qibla Compass & Alignment Alert',
      'feature_5': '📶 Offline Caching & Auto Re-sync',
      'feature_6': '🌍 Multilingual TR & EN Support',
      'license': 'License',
      'mit_license': 'MIT Open Source License',
      'rate_app': 'Rate App & Send Feedback',
      'github_repo': 'GitHub Repository (Open Source Code)',
      'theme_selection': 'App Theme 🎨',
      'theme_system': 'System 📱',
      'theme_light': 'Light ☀️',
      'theme_dark': 'Dark 🌙',
      'retry': 'Retry',
      'prayer_load_error': 'Could not load prayer times',
      'use_gps_location': 'Get Location via GPS 📡',
      'select_city': 'Select City',
      'search_city': 'Search city...',
      'stop_audio': 'Stop Sound',
      'stop_adhan_playing': 'Adhan Playing... Stop Audio 🛑',
      'asr_school': 'Asr Calculation Method (School)',
      'asr_school_desc': 'Select calculation standard for Asr prayer',
      'asr_standard': 'Standard (Shafi\'i, Maliki, Hanbali)',
      'asr_hanafi': 'Hanafi Method (Asr-e-Sani)',
      'monthly_times': 'Monthly Timetable 🗓️',
      'monthly_title': 'Monthly Prayer Schedule 🗓️',
      'day': 'Day',
      'date': 'Date',
    },
  };

  static String get(String key, String langCode) {
    final lang = _localizedValues.containsKey(langCode) ? langCode : 'tr';
    return _localizedValues[lang]?[key] ?? _localizedValues['tr']?[key] ?? key;
  }
}
