class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    'tr': {
      'app_title': 'Ezan Hatırlatıcı',
      'settings': 'Ayarlar',
      'about': 'Hakkında',
      'qibla': 'Kıble Pusulası',
      'language': 'Dil Seçimi',
      'language_desc': 'Uygulama dilini değiştirin',
      'turkish': 'Türkçe 🇹🇷',
      'english': 'English 🇬🇧',
      'next_prayer': 'SONRAKİ VAKİT',
      'time_remaining': 'Kalan Süre',
      'todays_prayers': 'Bugünün Namaz Saatleri',
      'location': 'Konum',
      'change': 'Değiştir',
      'unknown': 'Bilinmiyor',
      'current_location': 'Mevcut Konum',
      'fajr': 'Sabah Namazı',
      'sunrise': 'Güneş',
      'dhuhr': 'Öğle Namazı',
      'asr': 'İkindi Namazı',
      'maghrib': 'Akşam Namazı',
      'isha': 'Yatsı Namazı',
      'notification_settings': 'Bildirim Ayarları 🔔',
      'notification_sound': 'Bildirim Sesi',
      'notification_sound_desc': 'Vakit yaklaştığında sesli uyarı ver',
      'vibration': 'Titreşim',
      'vibration_desc': 'Bildirim geldiğinde cihazı titreştir',
      'select_notification_sound': 'Bildirim Sesi Seçimi',
      'select_sound_sub': 'Namaz vakti veya hatırlatmada çalacak olan sesi tercih edin:',
      'sound_makkah': 'Mekke Ezanı 🕋',
      'sound_makkah_sub': 'Klasik ve heybetli Mekke-i Mükerreme Ezanı',
      'sound_madinah': 'Medine Ezanı 🕌',
      'sound_madinah_sub': 'Huzur veren Medine-i Münevvere Ezanı',
      'sound_istanbul': 'İstanbul Ezanı 🇹🇷',
      'sound_istanbul_sub': 'Geleneksel Türk makamında İstanbul Ezanı',
      'sound_cairo': 'Mısır Ezanı 🇪🇬',
      'sound_cairo_sub': 'Mısır makamında yanık ve etkileyici Ezan',
      'sound_aqsa': 'Mescid-i Aksa Ezanı 🇵🇸',
      'sound_aqsa_sub': 'Kudüs Mescid-i Aksa ruhunu yansıtan Ezan',
      'adhan_makkah': 'Mekke-i Mükerreme Ezanı 🕋',
      'adhan_madinah': 'Medine-i Münevvere Ezanı 🕌',
      'adhan_istanbul': 'İstanbul (Türkiye) Ezanı 🇹🇷',
      'adhan_cairo': 'Mısır (Kahire) Ezanı 🇪🇬',
      'adhan_aqsa': 'Mescid-i Aksa (Kudüs) Ezanı 🇵🇸',
      'sound_cagri': 'Çağrı Filmi Müziği 🎬',
      'sound_cagri_sub': 'Simgeleşmiş heybetli Çağrı filmi enstrümantal teması',
      'sound_chime': 'Kudüs & İslami Zil 🔔',
      'sound_chime_sub': 'Huzur veren tatlı kristal zil uyarısı',
      'sound_ney': 'Huzurlu Ney Tonu 🎶',
      'sound_ney_sub': 'Yumuşak ve dinlendirici enstrümantal ses',
      'sound_beep': 'Kısa Bip Sesi 🔔',
      'sound_beep_sub': 'Sade ve kısa uyarı tonu',
      'adhan_sound_settings': 'Ezan Vakti Ses Ayarları (Tam Vakit) 🕌',
      'adhan_sound_desc': 'Tam ezan vakti girdiğinde (0. dakika) çalacak ses',
      'reminder_sound_settings': 'Hatırlatıcı / Uyarı Ses Ayarları (Kala / Sonra) ⏰',
      'reminder_sound_desc': 'Vakit öncesinde veya sonrasında çalacak kısa uyarı sesi',
      'adhan_sound_toggle': 'Ezan Vakti Sesi Okunsun',
      'reminder_sound_toggle': 'Hatırlatıcı Uyarısı Çalsın',
      'select_adhan_sound': 'Ezan Vakti Sesi Seçimi 🕌',
      'select_reminder_sound': 'Hatırlatıcı / Uyarı Sesi Seçimi ⏰',
      'test_adhan_sound': 'Ezan Vakti Sesini Test Et 🕌',
      'test_reminder_sound': 'Hatırlatıcı Sesini Test Et ⏰',
      'test_notification': 'Test Bildirimi Gönder',
      'test_notification_sent': 'Test bildirimi gönderildi! 🔔',
      'reminder_times': 'Hatırlatma Süreleri ⏰',
      'reminder_times_desc': 'Vakit öncesinde (kala) veya vakit girdikten (sonra) ne zaman bildirim almak istediğinizi ayarlayın:',
      'on_time': 'Vakit girince',
      'min_before': 'dakika önce',
      'min_after': 'dakika sonra',
      'exact_time': 'Tam Vaktinde',
      'qibla_angle': 'Kıble Açısı',
      'distance_to_kaaba': 'Kâbe\'ye Uzaklık',
      'qibla_aligned': 'Kıble Yönündesiniz! 🕌',
      'qibla_guide': '💡 Telefonunuzu düz bir zeminde tutun ve sarı ok tam yukarı gelene kadar cihazınızı döndürün.',
      'device_heading': 'Cihaz Yönü (Pusula Ayarı)',
      'about_description': 'Ezan Hatırlatıcı, dünya genelinde doğru namaz vakitleri, canlı sayaçlar, özelleştirilebilir hatırlatmalar ve Kıble pusulası sunan modern bir İslami yardımcı uygulamadır.',
      'version': 'Sürüm',
      'developer': 'Geliştirici',
      'data_source': 'Veri Kaynağı',
      'audio_source': 'Ses Kaynakları',
      'aladhan_api': 'Aladhan REST API (Dünya genel namaz saatleri)',
      'audio_recitations': 'Mekke & Medine Ezan Kayıtları (Haramain Audio)',
      'features': 'Öne Çıkan Özellikler',
      'feature_1': '⏱️ Canlı Vakit Geri Sayım Sayacı',
      'feature_2': '🔔 Özelleştirilebilir Zamanlanmış Bildirimler',
      'feature_3': '🕌 Mekke & Medine İnsan Sesli Ezan Kayıtları',
      'feature_4': '🧭 Hassas Kıble Pusulası & Hizalama Uyarısı',
      'feature_5': '📶 Çevrimdışı Önbellekleme Desteği',
      'feature_6': '🌍 Türkçe & İngilizce Çift Dil Desteği',
      'license': 'Lisans',
      'mit_license': 'MIT Açık Kaynak Lisansı',
      'rate_app': 'Uygulamayı Değerlendir & Geri Bildirim',
      'github_repo': 'GitHub Proje Deposu (Açık Kaynak Kodlar)',
      'theme_selection': 'Görünüm Teması 🎨',
      'theme_system': 'Sistem 📱',
      'theme_light': 'Aydınlık ☀️',
      'theme_dark': 'Karanlık 🌙',
      'retry': 'Tekrar Dene',
      'prayer_load_error': 'Namaz saatleri yüklenemedi',
      'use_gps_location': 'GPS ile Konumumu Al 📡',
      'select_city': 'Şehir Seç',
      'search_city': 'Şehir ara...',
      'stop_audio': 'Sesi Durdur',
      'stop_adhan_playing': 'Ezan Çalıyor... Sesi Durdur 🛑',
      'asr_school': 'İkindi Hesaplama Metodu (Mezhep)',
      'asr_school_desc': 'İkindi vakti hesaplama standardını belirleyin',
      'asr_standard': 'Standart (Şafiî, Malikî, Hanbelî)',
      'asr_hanafi': 'Hanefî (Asr-ı Sani)',
      'monthly_times': 'Aylık Takvim 🗓️',
      'monthly_title': 'Aylık Namaz Vakitleri 🗓️',
      'day': 'Gün',
      'date': 'Tarih',
      'exact_alarm_title': 'Tam Vaktinde Alarm İzni (Android 12+)',
      'exact_alarm_desc': 'Ezan vaktinde bildirimlerin gecikmeden tam saniyesinde çalabilmesi için Alarmlar & Hatırlatıcılar izninin açık olduğundan emin olun.',
      'request_exact_alarm': 'Tam Vakit Alarm İznini Kontrol Et ⏰',
      'color_theme': 'Renk Paleti & Ana Tema 🎨',
      'color_theme_desc': 'Uygulamanızın ana vurgu rengini seçin',
      'theme_green': 'Zümrüt 🌿',
      'theme_blue': 'Safir 💙',
      'theme_teal': 'Turkuaz 🌊',
      'theme_crimson': 'Lal 🔴',
      'theme_amber': 'Kehribar 👑',
      'calendar_dialog_title': 'Hicri & Miladi Takvim 🗓️',
      'calendar_dialog_desc': 'Bugünün Miladi & Hicri tarihi ve mübarek dini günler',
      'calc_method_title': 'Namaz Vakti Hesaplama Metodu 📐',
      'calc_method_desc': 'Namaz vakitlerinin alındığı resmi kurum ve takvim metodunu seçin',
      'ongoing_notification': 'Kalıcı Durum Çubuğu Bildirimi 📌',
      'ongoing_notification_desc': 'Bildirim çubuğunda canlı sıradaki vakti ve geri sayımı gösterir',
      'prayer_time_label': 'Vakti',
      'countdown_label': 'Geri Sayım',
      'friday_reminder': 'Cuma Günleri Özel Cuma Uyarısı 🕌',
      'friday_reminder_desc': 'Her Cuma günü Cuma namazına 1 saat kala özel mübarek cuma uyarısı gönderir',
      'sahur_reminder': 'İmsak Öncesi Sahur & Teheccüd Uyarısı 🌙',
      'sahur_reminder_desc': 'İmsak vaktine 45 dakika kala sahur ve gece ibadeti için özel uyarı gönderir',
      'method_13': 'Diyanet İşleri Başkanlığı (Türkiye & Avrupa) 🇹🇷',
      'method_13_desc': 'Türkiye, Belçika, Almanya, Fransa ve Avrupa camileri için resmi Diyanet takvimi.',
      'method_3': 'Dünya İslam Birliği (MWL - Muslim World League) 🌍',
      'method_3_desc': 'Avrupa ve dünya genelinde yaygın kullanılan hesaplama standardı.',
      'method_4': 'Ümmü\'l-Kurâ Üniversitesi (Mekke-i Mükerreme) 🕋',
      'method_4_desc': 'Suudi Arabistan ve Körfez ülkeleri resmi takvimi.',
      'method_5': 'Mısır Genel Ölçüm Heyeti (Egyptian General Survey) 🇪🇬',
      'method_5_desc': 'Mısır, Kuzey Afrika ve Ortadoğu hesaplaması.',
      'method_2': 'Kuzey Amerika İslam Cemiyeti (ISNA) 🇺🇸',
      'method_2_desc': 'Amerika ve Kanada genelinde kullanılan standart.',
      'method_12': 'Fransa İslami Örgütler Birliği (UOIF) 🇫🇷',
      'method_12_desc': 'Fransa özel 12 derece açılı yatsı ve imsak hesaplaması.',
      'method_15': 'Hilal Gözlem Komitesi (Moonsighting Committee) 🌙',
      'method_15_desc': 'Küresel rasathane ve gözlem esaslı takvim.',
    },
    'en': {
      'app_title': 'Prayer Times Reminder',
      'settings': 'Settings',
      'about': 'About',
      'qibla': 'Qibla Compass',
      'language': 'Language Selection',
      'language_desc': 'Change application language',
      'turkish': 'Türkçe 🇹🇷',
      'english': 'English 🇬🇧',
      'next_prayer': 'NEXT PRAYER',
      'time_remaining': 'Time Remaining',
      'todays_prayers': 'Today\'s Prayer Times',
      'location': 'Location',
      'change': 'Change',
      'unknown': 'Unknown',
      'current_location': 'Current Location',
      'fajr': 'Fajr (Dawn)',
      'sunrise': 'Sunrise',
      'dhuhr': 'Dhuhr (Noon)',
      'asr': 'Asr (Afternoon)',
      'maghrib': 'Maghrib (Sunset)',
      'isha': 'Isha (Night)',
      'notification_settings': 'Notification Settings 🔔',
      'notification_sound': 'Notification Sound',
      'notification_sound_desc': 'Play alert sound when prayer time approaches',
      'vibration': 'Vibration',
      'vibration_desc': 'Vibrate device upon notification',
      'select_notification_sound': 'Notification Sound Selection',
      'select_sound_sub': 'Choose your preferred recitation tone for prayer reminders:',
      'sound_makkah': 'Makkah Adhan 🕋',
      'sound_makkah_sub': 'Classic & majestic Makkah Al-Mukarramah Adhan',
      'sound_madinah': 'Madinah Adhan 🕌',
      'sound_madinah_sub': 'Peaceful Madinah Al-Munawwarah Adhan',
      'sound_istanbul': 'Istanbul Adhan 🇹🇷',
      'sound_istanbul_sub': 'Traditional Turkish style Istanbul Adhan',
      'sound_cairo': 'Cairo Adhan 🇪🇬',
      'sound_cairo_sub': 'Melodic & emotional Egyptian style Adhan',
      'sound_aqsa': 'Al-Aqsa Adhan 🇵🇸',
      'sound_aqsa_sub': 'Spiritual Adhan from Jerusalem Al-Aqsa',
      'sound_cagri': 'The Message Theme 🎬',
      'sound_cagri_sub': 'Iconic The Message movie instrumental theme',
      'sound_chime': 'Jerusalem Islamic Chime 🔔',
      'sound_chime_sub': 'Peaceful crystal bell alert',
      'sound_ney': 'Peaceful Ney Tone 🎶',
      'sound_ney_sub': 'Soft & relaxing instrumental sound',
      'sound_beep': 'Short Beep Tone 🔔',
      'sound_beep_sub': 'Simple and concise alert tone',
      'adhan_sound_settings': 'Exact Adhan Sound Settings 🕌',
      'adhan_sound_desc': 'Sound played at exact prayer time (0 min offset)',
      'reminder_sound_settings': 'Reminder / Warning Sound Settings ⏰',
      'reminder_sound_desc': 'Short warning sound for early or late prayer reminders',
      'adhan_sound_toggle': 'Play Adhan Sound at Exact Time',
      'reminder_sound_toggle': 'Play Warning Sound for Reminders',
      'select_adhan_sound': 'Select Adhan Sound 🕌',
      'select_reminder_sound': 'Select Reminder Warning Sound ⏰',
      'test_adhan_sound': 'Test Adhan Sound 🕌',
      'test_reminder_sound': 'Test Reminder Sound ⏰',
      'test_notification': 'Send Test Notification',
      'test_notification_sent': 'Test notification sent! 🔔',
      'reminder_times': 'Reminder Times ⏰',
      'reminder_times_desc': 'Set how many minutes before each prayer you wish to be notified:',
      'on_time': 'At prayer time',
      'min_before': 'min before',
      'exact_time': 'Exact Time',
      'qibla_angle': 'Qibla Angle',
      'distance_to_kaaba': 'Distance to Kaaba',
      'qibla_aligned': 'You are Facing Qibla! 🕌',
      'qibla_guide': '💡 Keep device flat and rotate until yellow arrow points directly up.',
      'device_heading': 'Device Heading (Compass Adjustment)',
      'about_description': 'Prayer Times Reminder is a modern Islamic utility app offering accurate global prayer schedules, live countdowns, custom reminders, and Qibla compass.',
      'version': 'Version',
      'developer': 'Developer',
      'data_source': 'Data Source',
      'audio_source': 'Audio Sources',
      'aladhan_api': 'Aladhan REST API (Global prayer timings)',
      'audio_recitations': 'Makkah & Madinah Vocal Recitations (Haramain Audio)',
      'features': 'Key Features',
      'feature_1': '⏱️ Live Prayer Countdown Timer',
      'feature_2': '🔔 Customizable Scheduled Local Notifications',
      'feature_3': '🕌 Authentic Makkah & Madinah Vocal Adhans',
      'feature_4': '🧭 Precision Qibla Compass & Alignment Alert',
      'feature_5': '📶 Offline Caching & Auto Re-sync',
      'feature_6': '🌍 Multilingual TR & EN Support',
      'license': 'License',
      'mit_license': 'MIT Open Source License',
      'rate_app': 'Rate App & Send Feedback',
      'github_repo': 'GitHub Repository (Open Source Code)',
      'theme_selection': 'App Theme 🎨',
      'theme_system': 'System 📱',
      'theme_light': 'Light ☀️',
      'theme_dark': 'Dark 🌙',
      'retry': 'Retry',
      'prayer_load_error': 'Could not load prayer times',
      'use_gps_location': 'Get Location via GPS 📡',
      'select_city': 'Select City',
      'search_city': 'Search city...',
      'stop_audio': 'Stop Sound',
      'stop_adhan_playing': 'Adhan Playing... Stop Audio 🛑',
      'asr_school': 'Asr Calculation Method (School)',
      'asr_school_desc': 'Select calculation standard for Asr prayer',
      'asr_standard': 'Standard (Shafi\'i, Maliki, Hanbali)',
      'asr_hanafi': 'Hanafi Method (Asr-e-Sani)',
      'monthly_times': 'Monthly Timetable 🗓️',
      'monthly_title': 'Monthly Prayer Schedule 🗓️',
      'day': 'Day',
      'date': 'Date',
      'exact_alarm_title': 'Exact Alarm Permission (Android 12+)',
      'exact_alarm_desc': 'Enable Alarms & Reminders permission so prayer notifications play exactly on time without delay.',
      'request_exact_alarm': 'Check Exact Alarm Permission ⏰',
      'color_theme': 'Color Palette & Theme 🎨',
      'color_theme_desc': 'Choose application primary accent color',
      'theme_green': 'Emerald 🌿',
      'theme_blue': 'Sapphire 💙',
      'theme_teal': 'Turquoise 🌊',
      'theme_crimson': 'Crimson 🔴',
      'theme_amber': 'Amber 👑',
      'calendar_dialog_title': 'Hijri & Gregorian Calendar 🗓️',
      'calendar_dialog_desc': 'Today\'s Gregorian & Hijri date and holy events',
      'calc_method_title': 'Calculation Method (Authority) 📐',
      'calc_method_desc': 'Select official authority and calendar method for prayer times',
      'ongoing_notification': 'Persistent Status Bar Notification 📌',
      'ongoing_notification_desc': 'Show live upcoming prayer time & countdown in notification shade',
      'prayer_time_label': 'Time',
      'countdown_label': 'Countdown',
      'friday_reminder': 'Special Blessed Friday Alert 🕌',
      'friday_reminder_desc': 'Send a special reminder 1 hour before Friday Dhuhr prayer',
      'sahur_reminder': 'Pre-Fajr Sahur & Tahajjud Alert 🌙',
      'sahur_reminder_desc': 'Send a wake-up reminder 45 minutes before Fajr/Imsak',
      'method_13': 'Diyanet İşleri Başkanlığı (Turkey & Europe) 🇹🇷',
      'method_13_desc': 'Official Diyanet calendar recommended for Turkey, Belgium, Germany & Europe.',
      'method_3': 'Muslim World League (MWL) 🌍',
      'method_3_desc': 'Standard calculation used across Europe and worldwide.',
      'method_4': 'Umm Al-Qura University (Makkah) 🕋',
      'method_4_desc': 'Official calendar for Saudi Arabia and Gulf nations.',
      'method_5': 'Egyptian General Authority of Survey 🇪🇬',
      'method_5_desc': 'Standard for Egypt, Africa and Middle East.',
      'method_2': 'Islamic Society of North America (ISNA) 🇺🇸',
      'method_2_desc': 'Standard used across USA and Canada.',
      'method_12': 'Union Organization Islamic de France (UOIF) 🇫🇷',
      'method_12_desc': 'Special French 12-degree Fajr & Isha calculation.',
      'method_15': 'Moonsighting Committee Worldwide 🌙',
      'method_15_desc': 'Global astronomical observation calendar.',
    },
  };

  static String get(String key, String langCode) {
    final lang = _localizedValues.containsKey(langCode) ? langCode : 'tr';
    return _localizedValues[lang]?[key] ?? _localizedValues['tr']?[key] ?? key;
  }
}
